services:
  db:
    image: postgres:15-alpine
    
    restart: always
    
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_cine_db
    
    ports:
      - "5432:5432"
    
    volumes:      
    # mapear el script local a la carpeta de docker
      - ./base-de-datos/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    tmpfs:
      - /var/lib/postgresql/data
