@host = http://localhost:3000

### Verificar estado del servidor (Root)
GET {{host}}/

### Obtener todas las películas (Lista vacía al inicio)
GET {{host}}/peliculas

### Crear una nueva película (201)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Terminator",
  "genero": "Accion"
}

### Crear otra película (201)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "El Padrino",
  "genero": "Drama"
}

### Crear otra película (201)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Star Wars",
  "genero": "Ciencia ficcion"
}

### Intentar crear película con titulo vacio (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "", 
  "genero": "Desconocido"
}

### Intentar crear película con genero vacio (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Star Wars", 
  "genero": ""
}

### Intentar crear película con titulo y genero vacios (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "", 
  "genero": ""
}

### Intentar crear una película sin pasar un titulo (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "genero": "Ciencia ficcion"
}

### Intentar crear una película sin pasar un genero (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Star Wars"
}

### Intentar crear una película sin pasar un titulo ni un genero (400)
POST {{host}}/peliculas
Content-Type: application/json

{}

### Obtener película por ID existente (Asumiendo que la primera creada es ID 1)
GET {{host}}/peliculas/1

### Obtener película por ID inexistente (404)
# Esto probará el bloque catch con 'PeliculaNoEncontradaError'
GET {{host}}/peliculas/9999

### Obtener una pelicula usando el titulo como filtro (200)
GET {{host}}/peliculas?titulo=Terminator

### Obtener una lista de peliculas con un titulo que no existe (200)
GET {{host}}/peliculas?titulo=tituloQueNoExiste

### Obtener una pelicula usando el genero como filtro (200)
GET {{host}}/peliculas?genero=Accion

### Obtener una lista de peliculas con un genero que no existe (200)
GET {{host}}/peliculas?genero=generoQueNoExiste

### Obtener una lista de peliculas buscando por titulo y genero (200)
GET {{host}}/peliculas?titulo=Terminator&genero=Accion

### Obtener una lista de peliculas con un titulo similar al filtro (fuzzy search) (200)
GET {{host}}/peliculas?titulo=Termi

### Obtener una lista de peliculas con un genero similar al filtro (fuzzy search) (200)
GET {{host}}/peliculas?genero=Acc

### Crear una nueva sala (201)
POST {{host}}/salas
Content-Type: application/json

{
  "capacidad": 50
}

### Crear otra nueva sala (201)
POST {{host}}/salas
Content-Type: application/json

{
  "capacidad": 100
}

### Crear otra nueva sala (201)
POST {{host}}/salas
Content-Type: application/json

{
  "capacidad": 150
}

### Intentar crear una sala con capacidad 0 (400)
POST {{host}}/salas
Content-Type: application/json

{
  "capacidad": 0
}

### Intentar crear una sala sin capacidad (400)
POST {{host}}/salas
Content-Type: application/json

{}

### Obtener todas las salas creadas (Lista vacia al inicio)
GET {{host}}/salas
Content-Type: application/json

{}

### Obtener todas las salas con una capacidad igual o mayor al parametro (Lista vacia al inicio)
GET {{host}}/salas?capacidad=100
Content-Type: application/json

{}

### Intentar obtener salas pasando una capacidad negativa (400)
GET {{host}}/salas?capacidad=-1
Content-Type: application/json

{}

### Intentar obtener salas pasando un valor no numerico como capacidad (400)
GET {{host}}/salas?capacidad=noEsUnNumero
Content-Type: application/json

{}

### Recuperar salas por id (asumiendo que hay una sala creada con el id pasado) (200)
GET {{host}}/salas/1
Content-Type: application/json

{}

### Intentar recuperar una sala con un id que no existe (asumiendo que no hay salas con id = 9999) (404)
GET {{host}}/salas/9999
Content-Type: application/json

{}

### Intentar recuperar una sala con un id que no es un numero (400)
GET {{host}}/salas/idInvalido
Content-Type: application/json

{}

### Crear una funcion (asumiendo una sala y una pelicula ya creadads) (200)
POST {{host}}/funciones/
Content-Type: application/json

{
  "idSala": 1,
  "idPelicula": 1
}

### Crear una funcion (asumiendo una sala y una pelicula ya creadads) (200)
POST {{host}}/funciones/
Content-Type: application/json

{
  "idSala": 2,
  "idPelicula": 2
}

### Obtener todas las funciones sin pasar parametros (inicialmente una lista vacia) (200)
GET {{host}}/funciones/
Content-Type: application/json

{}

### Obtener todas las funciones que tengan asiganadas la sala con el id pasado (inicialmente una lista vacia) (200)
GET {{host}}/funciones?idSala=1
Content-Type: application/json

{}

### Intentar buscar salas con un valor no numerico como id de sala (400)
GET {{host}}/funciones?idSala=valorNoNumerico
Content-Type: application/json

{}

