@host = http://localhost:3000

### Verificar estado del servidor (Root)
GET {{host}}/

### Obtener todas las películas (Lista vacía al inicio)
GET {{host}}/peliculas

### Crear una nueva película (201)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Inception",
  "genero": "Ciencia Ficción"
}

### Crear otra película (201)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "El Padrino",
  "genero": "Drama"
}

### Intentar crear película con titulo vacio (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "", 
  "genero": "Desconocido"
}

### Intentar crear película con genero vacio (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Star Wars", 
  "genero": ""
}

### Intentar crear película con titulo y genero vacios (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "", 
  "genero": ""
}

### Intentar crear una película sin pasar un titulo (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "genero": "Ciencia ficcion"
}

### Intentar crear una película sin pasar un genero (400)
POST {{host}}/peliculas
Content-Type: application/json

{
  "titulo": "Star Wars"
}

### Intentar crear una película sin pasar un titulo ni un genero (400)
POST {{host}}/peliculas
Content-Type: application/json

{}

### Obtener película por ID existente (Asumiendo que la primera creada es ID 1)
GET {{host}}/peliculas/1

### Obtener película por ID inexistente (404)
# Esto probará el bloque catch con 'PeliculaNoEncontradaError'
GET {{host}}/peliculas/9999