name: API Cine CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}       
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
      DB_NAME: ${{ vars.DB_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"
          cache: "yarn"

      - name: docker
        run: |
          docker compose up -d
          echo "Inicializando base de datos con docker..."
          sleep 10

      - name: build.sh
        run: |
          ./build.sh
