name: API Cine CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"
          cache: "yarn"
      - name: build.sh
        run: |
          ./build.sh
