name: API Cine CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: password
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: docker
        run: |
          docker compose up
          sleep 3

      - name: node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"
          cache: "yarn"
      - name: build.sh
        run: |
          ./build.sh
